Fixed a couple of tests which could fail under certain circumstances:
- UtilJ2eeCompatTest: tests were order-dependent.

- MailUtilTest#testSendMail(): didn't pass if the JVM needs but doesn't have a required cert needed to connect to the mail server (added extra catch to not fail the test, as is already done when we can't connect to the mail server).

with the following exception:
javax.mail.MessagingException: Can't send command to SMTP host;
  nested exception is:
    javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[...]

This is needed in order to have a Sonar analysis at Apache infra [cfr. INFRA-5441]

git-svn-id: https://svn.apache.org/repos/asf/incubator/jspwiki/trunk@1410091 13f79535-47bb-0310-9956-ffa450edef68